name: Build ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push Frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: safyan1/parcel-delivery-system-frontend:latest

      - name: Build and Push Backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend-node
          file: ./backend-node/Dockerfile
          push: true
          tags: safyan1/parcel-delivery-system-backend:latest