name: Parcel Delivery CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend Image
        run: docker build -t safyan1/parcel-delivery-system-frontend:latest ./frontend

      - name: Build Backend Image
        run: docker build -t safyan1/parcel-delivery-system-backend:latest ./backend-node

      - name: Push Frontend Image
        run: docker push safyan1/parcel-delivery-system-frontend:latest

      - name: Push Backend Image
        run: docker push safyan1/parcel-delivery-system-backend:latest